# syntax examples: https://www.appveyor.com/docs/appveyor-yml/

# version format
version: 1.0.{build}

# branches to build
branches:
  only:
    - master

environment:
  # environment docs: https://www.appveyor.com/docs/build-environment/

  # global variables
  global:
    CMAKE: "C:\\Program Files (x86)\\cmake\\bin\\cmake.exe"

  matrix:
    # # Qt 5.6, Python 3.5 32-bit, MSVC2015 (v14)
    # - PYTHON: "C:\\Python35"
    #   QT: "C:\\Qt\\5.6\\msvc2015"
    #   PYSIDE_BRANCH: "5.6"
    #   OPENSSL: "C:\\OpenSSL-Win32\\bin"
    #   VS: "C:\\Program Files (x86)\\Microsoft Visual Studio 14.0\\VC\\vcvarsall.bat"
    #   ARCH: x86
    #   APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2015
    #   platform: x86
    #   fast_finish: true

    # Qt 5.6, Python 3.5 64-bit, MSVC2015 (v14)
    - PYTHON: "C:\\Python35-x64"
      QT: "C:\\Qt\\5.6\\msvc2015_64"
      PYSIDE_BRANCH: "5.6"
      OPENSSL: "C:\\OpenSSL-Win64\\bin"
      VS: "C:\\Program Files (x86)\\Microsoft Visual Studio 14.0\\VC\\vcvarsall.bat"
      ARCH: amd64
      APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2015
      platform: x64
      fast_finish: true

    # # Qt 5.6, Python 3.6 32-bit, MSVC2015 (v14)
    # - PYTHON: "C:\\Python36"
    #   QT: "C:\\Qt\\5.6\\msvc2015"
    #   PYSIDE_BRANCH: "5.6"
    #   OPENSSL: "C:\\OpenSSL-Win32\\bin"
    #   VS: "C:\\Program Files (x86)\\Microsoft Visual Studio 14.0\\VC\\vcvarsall.bat"
    #   ARCH: x86
    #   APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2015
    #   platform: x86
    #   fast_finish: true

    # # Qt 5.6, Python 3.6 64-bit, MSVC2015 (v14)
    # - PYTHON: "C:\\Python36-x64"
    #   QT: "C:\\Qt\\5.6\\msvc2015_64"
    #   PYSIDE_BRANCH: "5.6"
    #   OPENSSL: "C:\\OpenSSL-Win64\\bin"
    #   VS: "C:\\Program Files (x86)\\Microsoft Visual Studio 14.0\\VC\\vcvarsall.bat"
    #   ARCH: amd64
    #   APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2015
    #   platform: x64
    #   fast_finish: true

    # # Qt 5.9, Python 3.5 64-bit, MSVC2015 (v14)
    # - PYTHON: "C:\\Python35-x64"
    #   QT: "C:\\Qt\\5.9\\msvc2015_64"
    #   PYSIDE_BRANCH: "5.9"
    #   OPENSSL: "C:\\OpenSSL-Win64\\bin"
    #   VS: "C:\\Program Files (x86)\\Microsoft Visual Studio 14.0\\VC\\vcvarsall.bat"
    #   ARCH: amd64
    #   LIBCLANG_ZIP_FOLDER: http://download.qt.io/development_releases/prebuilt/libclang
    #   LIBCLANG_ZIP: libclang-release_39-windows-vs2015_64.7z
    #   APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2015
    #   platform: x64
    #   fast_finish: true


init:
  - pwd
  - SET PATH=%PYTHON%;%PYTHON%\\Scripts;%PATH%
  - python -c "import sys; x = sys.version; print(x)"
  - if defined VS call "%VS%" %ARCH%
  # - git clone --recursive --branch %PYSIDE_BRANCH% https://code.qt.io/pyside/pyside-setup.git C:\pyside-setup

install:
  # libclang required for PySide2 5.9 branch
  - if [%PYSIDE_BRANCH%]==[5.9] (curl -L -fsS -o %LIBCLANG_ZIP% %LIBCLANG_ZIP_FOLDER%/%LIBCLANG_ZIP%)
  - if [%PYSIDE_BRANCH%]==[5.9] (7z x %LIBCLANG_ZIP%)
  - if [%PYSIDE_BRANCH%]==[5.9] (SET LLVM_INSTALL_DIR=%CD%\libclang)

before_build:
  - pip install wheel


build_script:
  # - python C:\pyside-setup\setup.py bdist_wheel --ignore-git --standalone --no-examples --jom --qmake="%QT%\bin\qmake.exe" --openssl="%OPENSSL" --cmake="%CMAKE%"
  - python -c "print('build here')"

# disable automatic MSVC builds
build: off

after_build:
  - mkdir %CD%\artifacts
  - xcopy "C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\*.bat" %CD%\artifacts


before_test:
  # - dir C:\pyside-setup\dist\*.whl
  # - pip install C:\pyside-setup\dist\PySide2*.whl
  - echo "before test"
  - dir %CD%\artifacts

# very simple test, not actually sufficient to test the standalone wheel
test_script:
  # - python -c "import PySide2"
  - python -c "print('test')"

artifacts:
  - path: artifacts\*.bat

